const fs = require("fs");
const code = [
  '/**',
  ' * ShengShi calculator - ported from calc_e.py',
  ' */',
  'import { loadGameData } from "./dataLoader";',
  '',
  'interface StoneEntry { lv: number; jf: number; stage: boolean; stage_jf: number; }',
  'interface XuanEntry { lv: number; jf: number; item: number; stage: boolean; stage_jf: number; }',
  'interface GangEntry { lv: number; jf: number; item: number; stage: boolean; stage_jf: number; stage_item: number; }',
  'type AnyEntry = StoneEntry | XuanEntry | GangEntry;',
  '',
  'let STONE_BY_LVL: Record<number, StoneEntry> = {};',
  'let XUAN_BY_LVL: Record<number, XuanEntry> = {};',
  'let GANG_BY_LVL: Record<number, GangEntry> = {};',
  'export let SLOT_LIMITS: Record<string, number> = {};',
  'let _loaded = false;',
  '',
  'export async function ensureData(): Promise<void> {',
  '  if (_loaded) return;',
  '  const json = await loadGameData("shengshi_data.json");',
  '  SLOT_LIMITS = json.slot_limits as Record<string, number>;',
  '  const stoneRaw: number[][] = json.stone_raw;',
  '  const xuanRaw: number[][] = json.xuan_raw;',
  '  const gangRaw: number[][] = json.gang_raw;',
  '  for (const r of stoneRaw) {',
  '    const e: StoneEntry = { lv: r[0], jf: r[1], stage: r[2] > 0, stage_jf: r[2] };',
  '    STONE_BY_LVL[e.lv] = e;',
  '  }',
  '  for (const r of xuanRaw) {',
  '    const e: XuanEntry = { lv: r[0], jf: r[1], item: r[2], stage: r[3] > 0, stage_jf: r[3] };',
  '    XUAN_BY_LVL[e.lv] = e;',
  '  }',
  '  for (const r of gangRaw) {',
  '    const e: GangEntry = { lv: r[0], jf: r[1], item: r[2], stage: r[3] > 0, stage_jf: r[3], stage_item: r[4] };',
  '    GANG_BY_LVL[e.lv] = e;',
  '  }',
  '  _loaded = true;',
  '}',
  '',
  'function getDataMap(slot: string): Record<number, AnyEntry> {',
  '  if (slot.includes("\\u5723\\u77F3")) return STONE_BY_LVL;',
  '  if (slot.includes("\\u7384\\u77F3")) return XUAN_BY_LVL;',
  '  return GANG_BY_LVL;',
  '}',
  '',
  'function hasItems(slot: string): boolean {',
  '  return !slot.includes("\\u5723\\u77F3");',
  '}',
  '',
  'export interface CalcByMaterialsResult {',
  '  level: number; totalJf: number; totalItem: number;',
  '  steps: number; remainingJf: number; remainingItem: number;',
  '}',
  '',
  'export async function calcByMaterials(',
  '  slot: string, curLv: number, jf: number, itemVal: number',
  '): Promise<CalcByMaterialsResult> {',
  '  await ensureData();',
  '  const maxLv = SLOT_LIMITS[slot] ?? 120;',
  '  const dataMap = getDataMap(slot);',
  '  let lv = curLv, totalJf = 0, totalItem = 0, steps = 0, remJf = jf, remItem = itemVal;',
  '  while (lv < maxLv) {',
  '    const nextLv = lv + 1;',
  '    const entry = dataMap[nextLv] as any;',
  '    if (!entry) break;',
  '    const needJf: number = entry.jf ?? 0;',
  '    const needItem: number = entry.item ?? 0;',
  '    const stageJf: number = entry.stage_jf ?? 0;',
  '    const stageItem: number = entry.stage_item ?? 0;',
  '    if (entry.stage && stageJf > 0) {',
  '      if (remJf !== Infinity && remJf < stageJf) break;',
  '      if (remJf !== Infinity) { remJf -= stageJf; totalJf += stageJf; }',
  '      if (remItem !== Infinity && stageItem > 0 && remItem < stageItem) break;',
  '      if (remItem !== Infinity && stageItem > 0) { remItem -= stageItem; totalItem += stageItem; }',
  '    }',
  '    let costOk = true;',
  '    if (needJf > 0) {',
  '      if (remJf !== Infinity && remJf < needJf) costOk = false;',
  '      else if (remJf !== Infinity) { remJf -= needJf; totalJf += needJf; }',
  '    }',
  '    if (needItem > 0 && hasItems(slot)) {',
  '      if (remItem !== Infinity && remItem < needItem) costOk = false;',
  '      else if (remItem !== Infinity) { remItem -= needItem; totalItem += needItem; }',
  '    }',
  '    if (!costOk) break;',
  '    lv = nextLv; steps++;',
  '  }',
  '  return { level: lv, totalJf, totalItem, steps, remainingJf: remJf, remainingItem: remItem };',
  '}',
  '',
  'export interface CalcForTargetResult {',
  '  totalJf: number; totalItem: number; stagesHit: number[];',
  '}',
  '',
  'export async function calcForTarget(',
  '  slot: string, startLv: number, targetLv: number',
  '): Promise<CalcForTargetResult> {',
  '  await ensureData();',
  '  const dataMap = getDataMap(slot);',
  '  let totalJf = 0, totalItem = 0;',
  '  const stagesHit: number[] = [];',
  '  for (let lv = startLv + 1; lv <= targetLv; lv++) {',
  '    const entry = dataMap[lv] as any;',
  '    if (!entry) continue;',
  '    totalJf += entry.jf ?? 0;',
  '    totalItem += entry.item ?? 0;',
  '    if (entry.stage) {',
  '      totalJf += entry.stage_jf ?? 0;',
  '      totalItem += entry.stage_item ?? 0;',
  '      stagesHit.push(lv);',
  '    }',
  '  }',
  '  return { totalJf, totalItem, stagesHit };',
  '}',
].join("\n");

fs.writeFileSync(
  "f:/Bricezyxu_Tool/Bricezyxu-Tool/V23-tauri/src/calculators/calcShengShi.ts",
  code,
  "utf8"
);
console.log("Written", code.length, "chars");
